### ISSUE TITLE
NameError: global name 'DeconvBNLayer' is not defined

### ISSUE THREAD

**Issue by jiangtaoo2333** [sfzhang15/RefineDet#124]
sir,thanks for u coding. what should i do to solve this problem.

python examples/refinedet/VGG16_VOC2007_320.py
Traceback (most recent call last):
  File "examples/refinedet/VGG16_VOC2007_320.py", line 430, in <module>
    AddExtraLayers(net, use_batchnorm, arm_source_layers, normalizations, lr_mult=lr_mult)
  File "examples/refinedet/VGG16_VOC2007_320.py", line 61, in AddExtraLayers
    DeconvBNLayer(net, from_layer, out_layer, use_batchnorm, False, 256, 2, 0, 2, lr_mult=lr_mult)
NameError: global name 'DeconvBNLayer' is not defined

**Comment by jiangtaoo2333** [comment]
The problem has been solved
