### ISSUE TITLE
关于训练自己的数据集（二分类）

### ISSUE THREAD

**Issue by lillyro** [sfzhang15/RefineDet#141]
您好，想问下我在训练自己数据集的时候只保留了person这个类。然后本来voc中label标签序号是15我修改为1。
在验证mAP时想使用自己的验证集时发现只支持voc数据集的测试，想问下我对应的需要修改的文件有哪些呢？然后是否我还是将person 的label标记为15比较好。谢谢！

**Comment by lillyro** [comment]
im_detect: 1760/1763
im_detect: 1761/1763
im_detect: 1762/1763
im_detect: 1763/1763
Evaluating detections
Writing person VOC results file
VOC07 metric? Yes
Traceback (most recent call last):
  File "test/refinedet_test_voc.py", line 60, in <module>
    single_scale_test_net(net, imdb, targe_size=input_size)
  File "/home/lilly/loli/RefineDet/test/lib/fast_rcnn/test.py", line 247, in single_scale_test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/home/lilly/loli/RefineDet/test/lib/datasets/pascal_voc.py", line 323, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/home/lilly/loli/RefineDet/test/lib/datasets/pascal_voc.py", line 292, in _do_python_eval
    use_07_metric=use_07_metric)
  File "/home/lilly/loli/RefineDet/test/lib/datasets/voc_eval.py", line 126, in voc_eval
    R = [obj for obj in recs[imagename] if obj['name'] == classname]
KeyError: 'set07_V002_I01469_usatest'

在验证准确率时提示错误如上，但是对应的XML文件中只含person。不太理解这个错误因为什么原因导致的

**Comment by chaobeiying** [comment]
@lillyro 你只有一类的话，应该把标签改为2，而不是1 ，因为第一类默认的是背景

**Comment by lillyro** [comment]
> @lillyro 你只有一类的话，应该把标签改为2，而不是1 ，因为第一类默认的是背景

第一类背景的标签是0，所以我的person标签就是1啊。

**Comment by sfzhang15** [comment]
@lillyro 
你好，把num_class改成2，同时做一个新的label_map.txt，类似voc

**Comment by lillyro** [comment]
@sfzhang15 
谢谢，之前二分类的问题解决了。由于我用的caltech数据集进行训练及验证，得到mAP为0.43。为了对比体现，我使用下载的您提供的模型在voc上进行验证，得到的结果如下
Reading annotation for 4901/4952
Saving cached annotations to /home/lilly/data/VOCdevkit/annotations_cache/annots.pkl
AP for person = 0.0004
Mean AP = 0.0004
~~~~~~~~
Results:
0.000
0.000
~~~~~~~~
想问下这里是否和我之前改动了分类有关呢？我将refinedet_test.py中的模型路径恢复为之前voc模型路径得到的mAP就变成了0.0004，用的模型是您百度网盘提供的VOC0712_refinedet_vgg16_320x320_final.caffemodel

**Comment by sfzhang15** [comment]
@lillyro 
你好，请问你是把label_map.txt里面的person这一类从15改成了1吗？如果你想直接用我们提供的VOC训好的模型，只用来检person这一类的，那你在测试的时候，只需要把15这一类的结果保存就好了。

**Comment by lillyro** [comment]
@sfzhang15 
您好，我是想验证mAP，然后在恢复过程中我的labelmap维持的是之前的20类，但是运行结果只显示了person的AP，然后数值还只有0.0004。所以有点迷茫。谢谢！

**Comment by yisiyinheluojiutian** [comment]
> 您好，想问下我在训练自己数据集的时候只保留了person这个类。然后本来voc中label标签序号是15我修改为1。
> 在验证mAP时想使用自己的验证集时发现只支持voc数据集的测试，想问下我对应的需要修改的文件有哪些呢？然后是否我还是将person 的label标记为15比较好。谢谢！

你好，请问如果只检测比如VOC中某一类别的物体具体需要修改哪些内容呢？
