### ISSUE TITLE
关于如何训练更小更快的网络，保留ARM和ODM模块？

### ISSUE THREAD

**Issue by urbaneman** [sfzhang15/RefineDet#143]
您好，感谢你做的研究与贡献，拜读了你的论文和部分开源代码，受益良多。有两个问题想请教您。（由于英文水平不是很高，怕描述不清，所以使用中文，希望您不要介意）。
1.考虑到使用VGG16和ResNet-101作为特征提取模块参数量较大，不能很好的满足实时性的要求，拟使用MobileNet或MobileNetV2或其他的模块来作为特征提取模块，来减少参数量以提高效率，模型中保留ARM和ODM模块。关于在特征提取阶段使用什么模块，不知道你有没有什么建议？
2.数据集制作过程中，如果只检测voc的20类目标，或者更少，关于coco数据集的lmdb数据集制作需要包含不含这些目标的图片吗？如果包含，占比大概多少能较好地训练出结果？
3.不采用fine-tuning的情况下，训练过程如何进行？超参数和梯度下降策略使用什么较好？有没有一些技巧可以传授一下。
接触目标检测不久，希望您能不吝赐教，感谢之至。

**Comment by wait1988** [comment]
@urbaneman 你加入CFE之后在MoileNetV2-SSD上提升大吗

**Comment by urbaneman** [comment]
我试着加入了，因为没有在imagenet上预训练，最后的结果voc07test只有60多，后来因为忙其他的事情，没有继续做实验，所以最终的结果怎么样，我也不确定。

**Comment by china56321** [comment]
请问refinedet只支持ResNet-101吗？可以将ResNet-101改为ResNet-50吗？我查了下资料，ResNet-101和ResNet-50不同之处在于conv4_x，ResNet50有6个block，而ResNet101有23个block，相差了17个block，也就是17 x 3 = 51层。在Refinedet/python/caffe文件夹里有个model_libs.py，是不是只需要将for i in range(1, 23)更改为for i in range(1, 6)就可以训练ResNet-50了吗？（加载ResNet-50.caffemodel）

**Comment by sfzhang15** [comment]
@china56321 
其他网络也可以训练的，只要你定义好，找到对的预训练模型就行。ResNet101到ResNet50应该就是按照你说的那么改。

**Comment by china56321** [comment]
博主好，我的目的是将ResNet-101改为ResNet-50。所以我在RefineDet/python/caffe/model_libs.py里新建了一个 ResNet50Body函数（直接将 ResNet101Body复制过来的），并将for i in range(1, 23)更改为for i in range(1, 6)，同时将ResNet101_COCO_320.py里的调用函数ResNet101Body(net, from_layer='data', use_pool5=False, use_dilation_conv5=False)改为ResNet50Body(net, from_layer='data', use_pool5=False, use_dilation_conv5=False)，但是执行训练命令时报错：Traceback (most recent call last):
  File "examples/refinedet/ResNet50_COCO_320.py", line 415, in <module>
    AddExtraLayers(net, arm_source_layers, use_batchnorm=True)
  File "examples/refinedet/ResNet50_COCO_320.py", line 31, in AddExtraLayers
    ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 256, 3, 1, 1)
  File "/home/lifan/share/make/RefineDet/python/caffe/model_libs.py", line 66, in ConvBNLayer
    net[conv_name] = L.Convolution(net[from_layer], num_output=num_output,
  File "/home/lifan/share/make/RefineDet/python/caffe/net_spec.py", line 193, in __getitem__
    return self.__getattr__(item)
  File "/home/lifan/share/make/RefineDet/python/caffe/net_spec.py", line 187, in __getattr__
    return self.tops[name]
KeyError: 'res4b22_relu'
请问以这种方式将resnet101替换为resnet50，还有其它参数需要设置吗？

**Comment by china56321** [comment]
可以不用预训练模型（resnet101或者resnet50或其它预训练模型）进行训练吗？若可以，这个流程是怎样的?
