### ISSUE TITLE
too many indices for array

### ISSUE THREAD

**Issue by ouchjm** [sfzhang15/RefineDet#161]
arm_source_layers = ['conv3_3', 'conv4_3', 'conv5_3', 'fc7', 'conv6_2']
odm_source_layers = ['P2', 'P3', 'P4', 'P5', 'P6']

多了一个特征层，然后训练的时候没有报错，测试的时候出现

Traceback (most recent call last):
  File "test/refinedet_test.py", line 39, in <module>
    single_scale_test_net(net, imdb, targe_size=input_size)
  File "/opt/caffe/test/lib/fast_rcnn/test.py", line 247, in single_scale_test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/opt/caffe/test/lib/datasets/pascal_voc.py", line 302, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/opt/caffe/test/lib/datasets/pascal_voc.py", line 271, in _do_python_eval
    use_07_metric=use_07_metric)
  File "/opt/caffe/test/lib/datasets/voc_eval.py", line 148, in voc_eval
    BB = BB[sorted_ind, :]
IndexError: too many indices for array
请问该如何解决？

**Comment by sfzhang15** [comment]
@ouchjm 
只根据目前这些信息我也不好判断是哪里的问题，你可以参考https://www.ibm.com/developerworks/cn/linux/l-cn-pythondebugger/index.html进行单步调试看看问题在哪里。

**Comment by ouchjm** [comment]
@sfzhang15 
谢谢学长，我已经按照SSD的测试方法解决了。
