### ISSUE TITLE
draw_net.py doesn't work

### ISSUE THREAD

**Issue by fukatani** [sfzhang15/RefineDet#39]
I tried draw_net.py to visualize net structure, but it doesn't work.

```
> python2 ./draw_net.py ../src/caffe/proto/caffe.proto graph.png
Traceback (most recent call last):
  File "./draw_net.py", line 58, in <module>
    main()
  File "./draw_net.py", line 44, in main
    text_format.Merge(open(args.input_net_proto_file).read(), net)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.5.1-py2.7.egg/google/protobuf/text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.5.1-py2.7.egg/google/protobuf/text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.5.1-py2.7.egg/google/protobuf/text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.5.1-py2.7.egg/google/protobuf/text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.5.1-py2.7.egg/google/protobuf/text_format.py", line 703, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 1:1 : Message type "caffe.NetParameter" has no field named "syntax".
```

I appreciate if anyone can resolve this error. Thanks.

**Comment by fukatani** [comment]
Sorry, I resolved this issue by myself. Thanks!
